# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(630, 400)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.l_conn2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_conn2.sizePolicy().hasHeightForWidth())
        self.l_conn2.setSizePolicy(sizePolicy)
        self.l_conn2.setObjectName(_fromUtf8("l_conn2"))
        self.gridLayout.addWidget(self.l_conn2, 2, 4, 1, 4)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.pb_send2 = QtGui.QPushButton(self.centralwidget)
        self.pb_send2.setEnabled(False)
        self.pb_send2.setObjectName(_fromUtf8("pb_send2"))
        self.gridLayout.addWidget(self.pb_send2, 4, 7, 1, 1)
        self.e_thrust1 = QtGui.QLineEdit(self.centralwidget)
        self.e_thrust1.setEnabled(False)
        self.e_thrust1.setObjectName(_fromUtf8("e_thrust1"))
        self.gridLayout.addWidget(self.e_thrust1, 4, 1, 1, 2)
        self.pb_disc2 = QtGui.QPushButton(self.centralwidget)
        self.pb_disc2.setEnabled(False)
        self.pb_disc2.setObjectName(_fromUtf8("pb_disc2"))
        self.gridLayout.addWidget(self.pb_disc2, 1, 7, 1, 1)
        self.pb_conn2 = QtGui.QPushButton(self.centralwidget)
        self.pb_conn2.setEnabled(False)
        self.pb_conn2.setObjectName(_fromUtf8("pb_conn2"))
        self.gridLayout.addWidget(self.pb_conn2, 1, 6, 1, 1)
        self.pb_send1 = QtGui.QPushButton(self.centralwidget)
        self.pb_send1.setEnabled(False)
        self.pb_send1.setObjectName(_fromUtf8("pb_send1"))
        self.gridLayout.addWidget(self.pb_send1, 4, 3, 1, 1)
        self.e_thrust2 = QtGui.QLineEdit(self.centralwidget)
        self.e_thrust2.setEnabled(False)
        self.e_thrust2.setObjectName(_fromUtf8("e_thrust2"))
        self.gridLayout.addWidget(self.e_thrust2, 4, 5, 1, 2)
        self.pb_disc1 = QtGui.QPushButton(self.centralwidget)
        self.pb_disc1.setEnabled(False)
        self.pb_disc1.setObjectName(_fromUtf8("pb_disc1"))
        self.gridLayout.addWidget(self.pb_disc1, 1, 3, 1, 1)
        self.pb_conn1 = QtGui.QPushButton(self.centralwidget)
        self.pb_conn1.setEnabled(False)
        self.pb_conn1.setCheckable(False)
        self.pb_conn1.setObjectName(_fromUtf8("pb_conn1"))
        self.gridLayout.addWidget(self.pb_conn1, 1, 2, 1, 1)
        self.cb_device1 = QtGui.QComboBox(self.centralwidget)
        self.cb_device1.setObjectName(_fromUtf8("cb_device1"))
        self.gridLayout.addWidget(self.cb_device1, 1, 0, 1, 2)
        self.cb_device2 = QtGui.QComboBox(self.centralwidget)
        self.cb_device2.setObjectName(_fromUtf8("cb_device2"))
        self.gridLayout.addWidget(self.cb_device2, 1, 4, 1, 2)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 4, 1, 1)
        self.l_conn1 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_conn1.sizePolicy().hasHeightForWidth())
        self.l_conn1.setSizePolicy(sizePolicy)
        self.l_conn1.setObjectName(_fromUtf8("l_conn1"))
        self.gridLayout.addWidget(self.l_conn1, 2, 0, 1, 4)
        self.pb_scan = QtGui.QPushButton(self.centralwidget)
        self.pb_scan.setObjectName(_fromUtf8("pb_scan"))
        self.gridLayout.addWidget(self.pb_scan, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.l_x2 = QtGui.QLabel(self.groupBox_2)
        self.l_x2.setObjectName(_fromUtf8("l_x2"))
        self.verticalLayout_2.addWidget(self.l_x2)
        self.l_y2 = QtGui.QLabel(self.groupBox_2)
        self.l_y2.setObjectName(_fromUtf8("l_y2"))
        self.verticalLayout_2.addWidget(self.l_y2)
        self.l_z2 = QtGui.QLabel(self.groupBox_2)
        self.l_z2.setObjectName(_fromUtf8("l_z2"))
        self.verticalLayout_2.addWidget(self.l_z2)
        self.gridLayout.addWidget(self.groupBox_2, 3, 4, 1, 4)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.l_x1 = QtGui.QLabel(self.groupBox)
        self.l_x1.setObjectName(_fromUtf8("l_x1"))
        self.verticalLayout.addWidget(self.l_x1)
        self.l_y1 = QtGui.QLabel(self.groupBox)
        self.l_y1.setObjectName(_fromUtf8("l_y1"))
        self.verticalLayout.addWidget(self.l_y1)
        self.l_z1 = QtGui.QLabel(self.groupBox)
        self.l_z1.setObjectName(_fromUtf8("l_z1"))
        self.verticalLayout.addWidget(self.l_z1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.l_conn2.setText(_translate("MainWindow", "Disconnected", None))
        self.label.setText(_translate("MainWindow", "Thrust:", None))
        self.pb_send2.setText(_translate("MainWindow", "Send", None))
        self.pb_disc2.setText(_translate("MainWindow", "Disconnect", None))
        self.pb_conn2.setText(_translate("MainWindow", "Connect", None))
        self.pb_send1.setText(_translate("MainWindow", "Send", None))
        self.pb_disc1.setText(_translate("MainWindow", "Disconnect", None))
        self.pb_conn1.setText(_translate("MainWindow", "Connect", None))
        self.label_7.setText(_translate("MainWindow", "Thrust:", None))
        self.l_conn1.setText(_translate("MainWindow", "Disconnected", None))
        self.pb_scan.setText(_translate("MainWindow", "Scan", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Accelometer 2", None))
        self.l_x2.setText(_translate("MainWindow", "x:", None))
        self.l_y2.setText(_translate("MainWindow", "y:", None))
        self.l_z2.setText(_translate("MainWindow", "z:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Accelometer 1", None))
        self.l_x1.setText(_translate("MainWindow", "x: ", None))
        self.l_y1.setText(_translate("MainWindow", "y: ", None))
        self.l_z1.setText(_translate("MainWindow", "z:", None))

