# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(724, 423)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.l_conn = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_conn.sizePolicy().hasHeightForWidth())
        self.l_conn.setSizePolicy(sizePolicy)
        self.l_conn.setObjectName(_fromUtf8("l_conn"))
        self.verticalLayout.addWidget(self.l_conn)
        self.gb_connection = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_connection.sizePolicy().hasHeightForWidth())
        self.gb_connection.setSizePolicy(sizePolicy)
        self.gb_connection.setObjectName(_fromUtf8("gb_connection"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gb_connection)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cb_device = QtGui.QComboBox(self.gb_connection)
        self.cb_device.setMinimumSize(QtCore.QSize(120, 20))
        self.cb_device.setObjectName(_fromUtf8("cb_device"))
        self.horizontalLayout.addWidget(self.cb_device)
        self.pb_scan = QtGui.QPushButton(self.gb_connection)
        self.pb_scan.setObjectName(_fromUtf8("pb_scan"))
        self.horizontalLayout.addWidget(self.pb_scan)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_conn = QtGui.QPushButton(self.gb_connection)
        self.pb_conn.setEnabled(False)
        self.pb_conn.setObjectName(_fromUtf8("pb_conn"))
        self.horizontalLayout.addWidget(self.pb_conn)
        self.pb_disc = QtGui.QPushButton(self.gb_connection)
        self.pb_disc.setEnabled(False)
        self.pb_disc.setObjectName(_fromUtf8("pb_disc"))
        self.horizontalLayout.addWidget(self.pb_disc)
        self.verticalLayout.addWidget(self.gb_connection)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gb_actual = QtGui.QGroupBox(self.frame_2)
        self.gb_actual.setMinimumSize(QtCore.QSize(80, 0))
        self.gb_actual.setObjectName(_fromUtf8("gb_actual"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gb_actual)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.l_x = QtGui.QLabel(self.gb_actual)
        self.l_x.setObjectName(_fromUtf8("l_x"))
        self.verticalLayout_3.addWidget(self.l_x)
        self.l_y = QtGui.QLabel(self.gb_actual)
        self.l_y.setObjectName(_fromUtf8("l_y"))
        self.verticalLayout_3.addWidget(self.l_y)
        self.l_z = QtGui.QLabel(self.gb_actual)
        self.l_z.setObjectName(_fromUtf8("l_z"))
        self.verticalLayout_3.addWidget(self.l_z)
        self.l_theta = QtGui.QLabel(self.gb_actual)
        self.l_theta.setObjectName(_fromUtf8("l_theta"))
        self.verticalLayout_3.addWidget(self.l_theta)
        self.horizontalLayout_2.addWidget(self.gb_actual)
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setMinimumSize(QtCore.QSize(80, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.l_vx = QtGui.QLabel(self.groupBox)
        self.l_vx.setObjectName(_fromUtf8("l_vx"))
        self.verticalLayout_6.addWidget(self.l_vx)
        self.l_vy = QtGui.QLabel(self.groupBox)
        self.l_vy.setObjectName(_fromUtf8("l_vy"))
        self.verticalLayout_6.addWidget(self.l_vy)
        self.l_vz = QtGui.QLabel(self.groupBox)
        self.l_vz.setObjectName(_fromUtf8("l_vz"))
        self.verticalLayout_6.addWidget(self.l_vz)
        self.l_vtheta = QtGui.QLabel(self.groupBox)
        self.l_vtheta.setObjectName(_fromUtf8("l_vtheta"))
        self.verticalLayout_6.addWidget(self.l_vtheta)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.gb_target = QtGui.QGroupBox(self.frame_2)
        self.gb_target.setEnabled(False)
        self.gb_target.setObjectName(_fromUtf8("gb_target"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gb_target)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.en_x = QtGui.QLineEdit(self.gb_target)
        self.en_x.setObjectName(_fromUtf8("en_x"))
        self.verticalLayout_4.addWidget(self.en_x)
        self.en_y = QtGui.QLineEdit(self.gb_target)
        self.en_y.setObjectName(_fromUtf8("en_y"))
        self.verticalLayout_4.addWidget(self.en_y)
        self.en_z = QtGui.QLineEdit(self.gb_target)
        self.en_z.setObjectName(_fromUtf8("en_z"))
        self.verticalLayout_4.addWidget(self.en_z)
        self.en_theta = QtGui.QLineEdit(self.gb_target)
        self.en_theta.setObjectName(_fromUtf8("en_theta"))
        self.verticalLayout_4.addWidget(self.en_theta)
        self.horizontalLayout_2.addWidget(self.gb_target)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.l_thrust_a = QtGui.QLabel(self.groupBox_2)
        self.l_thrust_a.setObjectName(_fromUtf8("l_thrust_a"))
        self.verticalLayout_7.addWidget(self.l_thrust_a)
        self.l_roll_a = QtGui.QLabel(self.groupBox_2)
        self.l_roll_a.setObjectName(_fromUtf8("l_roll_a"))
        self.verticalLayout_7.addWidget(self.l_roll_a)
        self.l_pitch_a = QtGui.QLabel(self.groupBox_2)
        self.l_pitch_a.setObjectName(_fromUtf8("l_pitch_a"))
        self.verticalLayout_7.addWidget(self.l_pitch_a)
        self.l_yaw_a = QtGui.QLabel(self.groupBox_2)
        self.l_yaw_a.setObjectName(_fromUtf8("l_yaw_a"))
        self.verticalLayout_7.addWidget(self.l_yaw_a)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.gb_ctrl_data = QtGui.QGroupBox(self.frame_2)
        self.gb_ctrl_data.setMinimumSize(QtCore.QSize(100, 0))
        self.gb_ctrl_data.setObjectName(_fromUtf8("gb_ctrl_data"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_ctrl_data)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.l_thrust = QtGui.QLabel(self.gb_ctrl_data)
        self.l_thrust.setObjectName(_fromUtf8("l_thrust"))
        self.verticalLayout_2.addWidget(self.l_thrust)
        self.l_roll = QtGui.QLabel(self.gb_ctrl_data)
        self.l_roll.setObjectName(_fromUtf8("l_roll"))
        self.verticalLayout_2.addWidget(self.l_roll)
        self.l_pitch = QtGui.QLabel(self.gb_ctrl_data)
        self.l_pitch.setObjectName(_fromUtf8("l_pitch"))
        self.verticalLayout_2.addWidget(self.l_pitch)
        self.l_yaw = QtGui.QLabel(self.gb_ctrl_data)
        self.l_yaw.setObjectName(_fromUtf8("l_yaw"))
        self.verticalLayout_2.addWidget(self.l_yaw)
        self.horizontalLayout_2.addWidget(self.gb_ctrl_data)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gb_control = QtGui.QGroupBox(self.frame_2)
        self.gb_control.setEnabled(False)
        self.gb_control.setObjectName(_fromUtf8("gb_control"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gb_control)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pb_start = QtGui.QPushButton(self.gb_control)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.verticalLayout_5.addWidget(self.pb_start)
        self.pb_update = QtGui.QPushButton(self.gb_control)
        self.pb_update.setObjectName(_fromUtf8("pb_update"))
        self.verticalLayout_5.addWidget(self.pb_update)
        self.pb_stop = QtGui.QPushButton(self.gb_control)
        self.pb_stop.setObjectName(_fromUtf8("pb_stop"))
        self.verticalLayout_5.addWidget(self.pb_stop)
        self.horizontalLayout_2.addWidget(self.gb_control)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.l_conn.setText(_translate("MainWindow", "Disconnected", None))
        self.gb_connection.setTitle(_translate("MainWindow", "Connection", None))
        self.pb_scan.setText(_translate("MainWindow", "Scan", None))
        self.pb_conn.setText(_translate("MainWindow", "Connect", None))
        self.pb_disc.setText(_translate("MainWindow", "Disconnect", None))
        self.gb_actual.setTitle(_translate("MainWindow", "Actual", None))
        self.l_x.setText(_translate("MainWindow", "X: ", None))
        self.l_y.setText(_translate("MainWindow", "Y: ", None))
        self.l_z.setText(_translate("MainWindow", "Z: ", None))
        self.l_theta.setText(_translate("MainWindow", "Kat: ", None))
        self.groupBox.setTitle(_translate("MainWindow", "Actual V", None))
        self.l_vx.setText(_translate("MainWindow", "Vx: ", None))
        self.l_vy.setText(_translate("MainWindow", "Vy: ", None))
        self.l_vz.setText(_translate("MainWindow", "Vz", None))
        self.l_vtheta.setText(_translate("MainWindow", "Vkat", None))
        self.gb_target.setTitle(_translate("MainWindow", "Target x,y,z,kat", None))
        self.en_x.setText(_translate("MainWindow", "0", None))
        self.en_y.setText(_translate("MainWindow", "0", None))
        self.en_z.setText(_translate("MainWindow", "40", None))
        self.en_theta.setText(_translate("MainWindow", "0", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Actual TRPY", None))
        self.l_thrust_a.setText(_translate("MainWindow", "Thrust:", None))
        self.l_roll_a.setText(_translate("MainWindow", "Roll:", None))
        self.l_pitch_a.setText(_translate("MainWindow", "Pitch", None))
        self.l_yaw_a.setText(_translate("MainWindow", "Yaw:", None))
        self.gb_ctrl_data.setTitle(_translate("MainWindow", "Control data", None))
        self.l_thrust.setText(_translate("MainWindow", "Thrust: ", None))
        self.l_roll.setText(_translate("MainWindow", "Roll:", None))
        self.l_pitch.setText(_translate("MainWindow", "Pitch:", None))
        self.l_yaw.setText(_translate("MainWindow", "Yaw:", None))
        self.gb_control.setTitle(_translate("MainWindow", "Control", None))
        self.pb_start.setText(_translate("MainWindow", "Start", None))
        self.pb_update.setText(_translate("MainWindow", "Update", None))
        self.pb_stop.setText(_translate("MainWindow", "Stop", None))

